# -*- coding: utf-8 -*-
"""sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dr2scZfhIEsZLceWHn2uiVmCAHAzVOsK
"""

# -*- coding: utf-8 -*-
"""sales.ipynb (Updated for Date column and growth analysis)"""

import streamlit as st
import pandas as pd
import json
from google.oauth2 import service_account
from googleapiclient.discovery import build

# ---------- Configuration ----------
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']
SPREADSHEET_ID = '1TTlOg7SbjIv1yWJksGxWODDNHrrV7S1NSFfHzxfmYlE'  # Your spreadsheet ID
RANGE_NAME = 'Sales!A:B'   # Sheet name and columns (Date in A, Sales in B)

def get_sheet_data():
    """Fetch data from Google Sheets using a service account."""
    creds_dict = json.loads(st.secrets["google_credentials"])
    creds = service_account.Credentials.from_service_account_info(
        creds_dict, scopes=SCOPES
    )
    service = build('sheets', 'v4', credentials=creds)
    sheet = service.spreadsheets()
    result = sheet.values().get(
        spreadsheetId=SPREADSHEET_ID,
        range=RANGE_NAME
    ).execute()
    values = result.get('values', [])
    if not values:
        return pd.DataFrame()
    header = values[0]
    data = values[1:]
    df = pd.DataFrame(data, columns=header)
    return df

@st.cache_data(ttl=600)  # Cache data for 10 minutes
def load_data():
    df = get_sheet_data()
    if df.empty:
        return df

    # Clean column names (trim spaces, lower case for easier matching)
    df.columns = [col.strip().lower() for col in df.columns]

    # Identify the date column (assume first column if not found)
    if 'date' in df.columns:
        date_col = 'date'
    else:
        # Use first column
        date_col = df.columns[0]
        st.info(f"Using '{date_col}' as the date column. Consider renaming to 'Date'.")

    # Identify the sales column (assume second column if not found)
    if 'sales' in df.columns or 'amount' in df.columns:
        sales_col = 'sales' if 'sales' in df.columns else 'amount'
    else:
        sales_col = df.columns[1]  # second column
        st.info(f"Using '{sales_col}' as the sales column. Consider renaming to 'Sales'.")

    # Convert date column to datetime
    df[date_col] = pd.to_datetime(df[date_col], errors='coerce')

    # Convert sales to numeric (strip commas, etc.)
    df[sales_col] = pd.to_numeric(df[sales_col].astype(str).str.replace(',', ''), errors='coerce')

    # Drop rows with invalid date or sales
    df = df.dropna(subset=[date_col, sales_col])

    # Extract year-month period
    df['Month'] = df[date_col].dt.to_period('M')

    # Aggregate sales by month
    monthly = df.groupby('Month')[sales_col].sum().reset_index()
    monthly['Month'] = monthly['Month'].astype(str)          # for display
    monthly.rename(columns={sales_col: 'Sales'}, inplace=True)

    # Calculate month‑over‑month growth
    monthly['Growth (%)'] = monthly['Sales'].pct_change() * 100
    monthly['Growth (%)'] = monthly['Growth (%)'].round(2)

    return monthly

# ---------- Streamlit UI ----------
st.set_page_config(page_title="Sales Dashboard", layout="centered")
st.title("📊 Monthly Sales & Growth Analysis")
st.markdown("Data loaded from Google Sheets: `Sales` sheet with **Date** and **Sales** columns.")

with st.spinner("Fetching latest data..."):
    data = load_data()

if data.empty:
    st.warning("No data to display. Please check the sheet and service account permissions.")
else:
    # Display the aggregated table
    st.subheader("Monthly Totals & Growth")
    st.dataframe(data)

    # Sales bar chart
    st.subheader("Monthly Sales")
    st.bar_chart(data.set_index('Month')['Sales'])

    # Growth line chart
    st.subheader("Month‑over‑Month Growth (%)")
    st.line_chart(data.set_index('Month')['Growth (%)'])

