# -*- coding: utf-8 -*-
"""sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dr2scZfhIEsZLceWHn2uiVmCAHAzVOsK
"""

import streamlit as st
import pandas as pd
import json
from google.oauth2 import service_account
from googleapiclient.discovery import build

# ---------- Configuration ----------
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']
SPREADSHEET_ID = '1TTlOg7SbjIv1yWJksGxWODDNHrrV7S1NSFfHzxfmYlE'  # Your spreadsheet ID
RANGE_NAME = 'Sales!A:B'   # Sheet name and columns (e.g., "Sales!A:B")

def get_sheet_data():
    """Fetch data from Google Sheets using a service account."""
    # Load service account info from Streamlit secrets
    creds_dict = json.loads(st.secrets["google_credentials"])
    creds = service_account.Credentials.from_service_account_info(
        creds_dict, scopes=SCOPES
    )
    service = build('sheets', 'v4', credentials=creds)
    sheet = service.spreadsheets()
    result = sheet.values().get(
        spreadsheetId=SPREADSHEET_ID,
        range=RANGE_NAME
    ).execute()
    values = result.get('values', [])
    if not values:
        return pd.DataFrame()
    header = values[0]
    data = values[1:]
    df = pd.DataFrame(data, columns=header)
    return df

@st.cache_data(ttl=600)  # Cache data for 10 minutes
def load_data():
    df = get_sheet_data()
    if df.empty:
        return df
    # Clean column names (trim spaces)
    df.columns = [col.strip() for col in df.columns]
    # Convert Month to datetime – assumes months like "January", "February"...
    df['Month'] = pd.to_datetime(df['Month'] + ' 2000', format='%B %Y')
    # Ensure Sales is numeric, handling commas
    df['Sales'] = pd.to_numeric(df['Sales'].astype(str).str.replace(',', ''), errors='coerce')
    # Drop rows with invalid Sales
    df = df.dropna(subset=['Sales'])
    # Aggregate by month (in case there are multiple entries per month)
    monthly = df.groupby(df['Month'].dt.to_period('M'))['Sales'].sum().reset_index()
    monthly['Month'] = monthly['Month'].astype(str)
    return monthly

# ---------- Streamlit UI ----------
st.set_page_config(page_title="Sales Dashboard", layout="centered")
st.title("📊 Sales per Month (from Google Sheets)")
st.markdown("Data loaded from Google Sheets: `Sales` sheet, columns `Month` and `Sales`")

with st.spinner("Fetching latest data..."):
    data = load_data()

if data.empty:
    st.warning("No data to display. Please check the sheet and service account permissions.")
else:
    st.subheader("Monthly Sales Data")
    st.dataframe(data)

    st.subheader("Bar Chart")
    st.bar_chart(data.set_index('Month'))

    st.subheader("Line Chart")
    st.line_chart(data.set_index('Month'))